package br.com.vcruz.stock.view;

import br.com.vcruz.stock.model.User;
import br.com.vcruz.stock.view.internal.ProductListView;
import br.com.vcruz.stock.view.internal.ProductRegisterView;
import br.com.vcruz.stock.view.internal.SaleView;
import br.com.vcruz.stock.view.internal.StockListView;
import br.com.vcruz.stock.view.internal.UserListView;
import br.com.vcruz.stock.view.internal.UserRegisterView;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vcruz
 */
public class DashboardView extends javax.swing.JFrame {

    public static User loggedUser;
    private static JInternalFrame currentlyOpenWindow;

    /**
     * Creates new form Dashboard
     *
     * @param user
     */
    public DashboardView(User user) {
        DashboardView.loggedUser = user;

        initComponents();

        if (DashboardView.loggedUser != null && DashboardView.loggedUser.isRoot()) {
            this.enableRootFeatures();
        }
    }

    private void enableRootFeatures() {
        this.userRegisterMenuItem.setEnabled(true);
        this.userListMenuItem.setEnabled(true);
    }

    private void exit() {
        Object[] options = {"Sim", "Não"};
        int exit = JOptionPane.showOptionDialog(this, "Tem certeza que deseja sair?", "Sair", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (JOptionPane.YES_OPTION == exit) {
            this.dispose();
            new LoginView().setVisible(true);
        }
    }

    public static void openInternalFrame(JInternalFrame frame) {
        DashboardView.rootWindowjDesktopPane.removeAll();
        if (DashboardView.currentlyOpenWindow != null) {
            DashboardView.currentlyOpenWindow.dispose();
        }
        DashboardView.currentlyOpenWindow = frame;
        DashboardView.currentlyOpenWindow.setVisible(true);
        DashboardView.rootWindowjDesktopPane.add(DashboardView.currentlyOpenWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        rootWindowjDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        saleMenu = new javax.swing.JMenu();
        saleMenuItem = new javax.swing.JMenuItem();
        saleListMenuItem = new javax.swing.JMenuItem();
        stockMenu = new javax.swing.JMenu();
        stockListMenuItem = new javax.swing.JMenuItem();
        productMenu = new javax.swing.JMenu();
        productRegisterMenuItem = new javax.swing.JMenuItem();
        productListMenuItem = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        userRegisterMenuItem = new javax.swing.JMenuItem();
        userListMenuItem = new javax.swing.JMenuItem();
        userProfileMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Stock - Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        rootWindowjDesktopPane.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(rootWindowjDesktopPane, java.awt.BorderLayout.CENTER);

        saleMenu.setText("Venda");

        saleMenuItem.setText("Vender");
        saleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleMenuItemActionPerformed(evt);
            }
        });
        saleMenu.add(saleMenuItem);

        saleListMenuItem.setText("Listagem");
        saleMenu.add(saleListMenuItem);

        jMenuBar1.add(saleMenu);

        stockMenu.setText("Estoque");

        stockListMenuItem.setText("Listagem");
        stockListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockListMenuItemActionPerformed(evt);
            }
        });
        stockMenu.add(stockListMenuItem);

        jMenuBar1.add(stockMenu);

        productMenu.setText("Produto");

        productRegisterMenuItem.setText("Cadastro");
        productRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productRegisterMenuItemActionPerformed(evt);
            }
        });
        productMenu.add(productRegisterMenuItem);

        productListMenuItem.setText("Listagem");
        productListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productListMenuItemActionPerformed(evt);
            }
        });
        productMenu.add(productListMenuItem);

        jMenuBar1.add(productMenu);

        userMenu.setText("Usuário");

        userRegisterMenuItem.setText("Cadastro");
        userRegisterMenuItem.setEnabled(false);
        userRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegisterMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userRegisterMenuItem);

        userListMenuItem.setText("Listagem");
        userListMenuItem.setEnabled(false);
        userListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userListMenuItem);

        userProfileMenuItem.setText("Perfil");
        userProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userProfileMenuItem);

        jMenuBar1.add(userMenu);

        exitMenu.setText("Sair");
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.exit();
    }//GEN-LAST:event_formWindowClosing

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        this.exit();
    }//GEN-LAST:event_exitMenuMouseClicked

    private void userRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegisterMenuItemActionPerformed
        DashboardView.openInternalFrame(new UserRegisterView(false));
    }//GEN-LAST:event_userRegisterMenuItemActionPerformed

    private void userListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListMenuItemActionPerformed
        DashboardView.openInternalFrame(new UserListView());
    }//GEN-LAST:event_userListMenuItemActionPerformed

    private void userProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileMenuItemActionPerformed
        DashboardView.openInternalFrame(new UserRegisterView(true));
    }//GEN-LAST:event_userProfileMenuItemActionPerformed

    private void productRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productRegisterMenuItemActionPerformed
        DashboardView.openInternalFrame(new ProductRegisterView());
    }//GEN-LAST:event_productRegisterMenuItemActionPerformed

    private void productListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productListMenuItemActionPerformed
        DashboardView.openInternalFrame(new ProductListView());
    }//GEN-LAST:event_productListMenuItemActionPerformed

    private void stockListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockListMenuItemActionPerformed
        DashboardView.openInternalFrame(new StockListView());
    }//GEN-LAST:event_stockListMenuItemActionPerformed

    private void saleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleMenuItemActionPerformed
        DashboardView.openInternalFrame(new SaleView());
    }//GEN-LAST:event_saleMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem productListMenuItem;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenuItem productRegisterMenuItem;
    private static javax.swing.JDesktopPane rootWindowjDesktopPane;
    private javax.swing.JMenuItem saleListMenuItem;
    private javax.swing.JMenu saleMenu;
    private javax.swing.JMenuItem saleMenuItem;
    private javax.swing.JMenuItem stockListMenuItem;
    private javax.swing.JMenu stockMenu;
    private javax.swing.JMenuItem userListMenuItem;
    private javax.swing.JMenu userMenu;
    private javax.swing.JMenuItem userProfileMenuItem;
    private javax.swing.JMenuItem userRegisterMenuItem;
    // End of variables declaration//GEN-END:variables
}
